#!/bin/sh
# The `h` controls help: xpdt's key bindings shown in a scrollable popup
# (popup.sh). Laid out vertically with short lines, so it never runs off the
# side of a narrow terminal (which the old always-on bottom panel did).
E=$(printf '\033')
H="${E}[1;38;5;81m"; K="${E}[38;5;215m"; D="${E}[38;5;250m"; Z="${E}[0m"
row() { printf "  ${K}%-12s${Z}${D}%s${Z}\n" "$1" "$2"; }
sec() { printf "\n  ${H}%s${Z}\n" "$1"; }
{
  sec "MOVE"
  row "up down" "navigate"
  row "right" "enter directory / preview file"
  row "left" "up a directory"
  row "'" "jump back to the start directory"
  row "q" "quit"
  sec "OPEN"
  row "enter" "repo changes browser"
  row ";" "commit history (git log)"
  row "s" "stash browser"
  row "/" "find files by name"
  row "\\" "search inside files"
  row "g" "git menu (status / fetch / checkout / pull)"
  row "," "settings (confirmations, hidden files)"
  row "h" "this help"
  row "ctrl-h" "neovim cheat sheet"
  sec "FILES  (2-digit confirm by default)"
  row "a" "create file"
  row "f" "create folder"
  row "m" "move / rename"
  row "d" "delete"
  sec "CHANGES BROWSER  (enter)"
  row "s" "stage / unstage the whole file"
  row "p" "stage / unstage individual hunks"
  row "d" "discard"
  row "c" "commit"
  row "ctrl-e" "edit in neovim"
  row "right" "inline diff viewer"
  row "enter" "open diff in VS Code"
  sec "HUNK BROWSER  (p in the changes browser)"
  row "s" "stage / unstage the focused hunk"
  row "d" "discard the hunk (unstaged only)"
  row "left" "back"
  sec "COMMIT HISTORY  (;)"
  row "right" "open a commit (browse its files)"
  row "b" "view a different branch's commits"
  row "ctrl-p" "cherry-pick the commit onto the current branch"
  row "ctrl-z" "undo the last commit"
  row "left" "back"
  sec "STASH BROWSER  (s)"
  row "a" "apply"
  row "p" "pop"
  row "d" "drop"
  row "n" "new"
  row "x" "clear all"
  row "right" "view diff"
  sec "FILE PREVIEW  (right on a file)"
  row "type" "filter lines"
  row "ctrl-y" "copy file to clipboard"
  row "ctrl-e" "edit at the line in neovim"
  row "enter" "file menu"
  sec "INLINE DIFF VIEWER"
  row "right" "next change"
  row "shift-right" "previous change"
  row "left" "back"
  sec "SEARCH  (/ and \\)"
  row "type" "filter"
  row "tab" "toggle scope (here / whole tree)"
  sec "SETTINGS  (,)"
  row "enter" "toggle the focused row (confirmations, show hidden files)"
  row "left" "close"
  printf "\n  ${D}%s${Z}\n" "(press q or h to close)"
} | sh "$HOME/.config/xpdt/popup.sh" "xpdt controls"
