#!/bin/sh
# The `h` controls help: xpdt's key bindings shown in a scrollable popup
# (popup.sh). Laid out vertically with short lines, so it never runs off the
# side of a narrow terminal (which the old always-on bottom panel did).
E=$(printf '\033')
H="${E}[1;38;5;81m"; K="${E}[38;5;215m"; D="${E}[38;5;250m"; Z="${E}[0m"
row() { printf "  ${K}%-12s${Z}${D}%s${Z}\n" "$1" "$2"; }
sec() { printf "\n  ${H}%s${Z}\n" "$1"; }
{
  sec "MOVE"
  row "up down" "navigate"
  row "right" "enter a directory, or open a file in neovim (preview first, if enabled)"
  row "left" "up a directory"
  row "'" "jump back to the start directory"
  row "w" "hop to the next sibling git repo (its top)"
  row "q" "quit"
  sec "OPEN"
  row "enter" "repo changes browser"
  row ";" "commit history (git log)"
  row "s" "stash browser"
  row "/" "find files by name"
  row "\\" "search inside files"
  row "g" "git menu (status / fetch / checkout / pull)"
  row "," "settings (theme, intellisense, previews, confirmations)"
  row "h" "this help"
  row "ctrl-h" "neovim cheat sheet"
  sec "FILES  (2-digit confirm by default)"
  row "a" "create file"
  row "f" "create folder"
  row "m" "rename (current name pre-filled - just edit it)"
  row "M" "move to a folder (fuzzy-pick it, no path typing)"
  row "d" "delete"
  sec "CHANGES BROWSER  (enter)"
  row "s" "stage / unstage the whole file"
  row "p" "stage / unstage individual hunks"
  row "d" "discard"
  row "c" "commit"
  row "ctrl-e" "edit in neovim"
  row "right" "edit (unstaged) / inline diff viewer (staged)"
  row "enter" "open diff in VS Code"
  row "left" "back"
  sec "HUNK BROWSER  (p in the changes browser)"
  row "s" "stage / unstage the focused hunk"
  row "d" "discard the hunk (unstaged only)"
  row "left" "back"
  sec "COMMIT HISTORY  (;)"
  row "right" "open a commit (browse its files)"
  row "b" "view a different branch's commits"
  row "ctrl-p" "cherry-pick the commit onto the current branch"
  row "ctrl-z" "undo the last commit"
  row "left" "back"
  sec "STASH BROWSER  (s)"
  row "a" "apply"
  row "p" "pop"
  row "d" "drop"
  row "n" "new"
  row "x" "clear all"
  row "right" "view diff"
  sec "FILE PREVIEW  (→ on a file, when enabled in settings)"
  row "type" "filter lines"
  row "ctrl-e" "open in neovim at the line"
  row "ctrl-y" "copy the whole file to the clipboard"
  row "enter" "file menu"
  row "left" "back"
  sec "INLINE DIFF VIEWER"
  row "right" "next change"
  row "shift-right" "previous change"
  row "left" "back"
  sec "SELECT / COPY TEXT  (any view)"
  row "opt-drag" "hold Option / ⌥ (macOS) and drag to select text, then copy"
  row "shift-drag" "or hold Shift instead (depends on the terminal)"
  row "" "- bypasses the mouse capture for a normal selection"
  row "right" "or open the file in neovim to v-select and y-yank"
  row "" "- <space>Y in neovim copies the whole file to the clipboard"
  sec "SEARCH  (/ and \\)"
  row "type" "filter"
  row "tab" "toggle scope (here / whole tree)"
  row "left" "delete back through the query; exit when it is empty"
  row "right" "open a file (\\: at the matched line), or enter a folder (/)"
  row "enter" "same as right (/), or the file menu (\\)"
  sec "SETTINGS  (,)"
  row "enter" "toggle a setting, or pick the focused theme"
  row "left" "close"
  printf "\n  ${D}%s${Z}\n" "(press q or h to close)"
} | sh "$HOME/.config/xpdt/popup.sh" "xpdt controls"
