#!/bin/sh
E=$(printf '\033')
H="${E}[1;38;5;81m"
K="${E}[38;5;215m"
D="${E}[38;5;250m"
Z="${E}[0m"
row() { printf "  ${K}%-12s${Z}${D}%s${Z}\n" "$1" "$2"; }
sec() { printf "\n  ${H}%s${Z}\n" "$1"; }
{
  printf "\n  ${H}%s${Z}\n" "NEOVIM CHEAT SHEET"
  sec "MOVE"
  row "s"          "leap: then type 2 characters to jump there"
  row "w"          "start of next word"
  row "b"          "start of previous word"
  row "e"          "end of word"
  row "0"          "start of line"
  row "\$"          "end of line"
  row "gg"         "top of file"
  row "G"          "bottom of file"
  row "{"          "previous paragraph"
  row "}"          "next paragraph"
  row "Ctrl-d"     "half page down"
  row "Ctrl-u"     "half page up"
  row "%"          "jump to matching bracket"
  row "f{c}"       "jump to next character c"
  row "*"          "search for the word under the cursor"
  sec "EDIT"
  row "i"          "insert before the cursor"
  row "a"          "insert after the cursor"
  row "A"          "insert at end of line"
  row "o"          "open a new line below"
  row "O"          "open a new line above"
  row "x"          "delete one character"
  row "dd"         "delete the line"
  row "cc"         "change the whole line"
  row "yy"         "yank (copy) the line"
  row "p"          "paste"
  row "u"          "undo"
  row "Ctrl-r"     "redo"
  row "."          "repeat the last change"
  row ">>"         "indent the line"
  row "<<"         "dedent the line"
  sec "SURROUND & COMMENT"
  row "ysiw\""      "surround the word with quotes"
  row "cs\"'"       "change surrounding double quotes to single"
  row "ds("        "delete the surrounding brackets"
  row "gcc"        "comment or uncomment the line"
  row "gc"         "comment a selection or motion"
  sec "SELECT & COPY"
  row "v"          "select characters"
  row "V"          "select whole lines"
  row "Ctrl-v"     "select a block"
  row "y"          "yank selection (copies to macOS clipboard)"
  row "d"          "delete the selection"
  row "c"          "change the selection"
  sec "SEARCH & SAVE"
  row "/text"      "search forwards for text"
  row "n"          "jump to next match"
  row "N"          "jump to previous match"
  row ":w"         "save"
  row ":q"         "quit"
  row ":wq"        "save and quit"
  row ":q!"        "quit without saving"
  printf "\n  ${D}%s${Z}\n" "(press q or ctrl-h to close)"
} | sh "$HOME/.config/xpdt/popup.sh" "neovim cheat sheet"
